// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMH0XbOOlTEsXFbxnT0acI3Z5IJA3H6M',
    appId: '1:884151832412:web:d4becad54dc696dffabb99',
    messagingSenderId: '884151832412',
    projectId: 'promisee-30dd7',
    authDomain: 'promisee-30dd7.firebaseapp.com',
    storageBucket: 'promisee-30dd7.appspot.com',
    measurementId: 'G-M98WE6MMJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkdtb6QX3HG96NNClNHM8vK9KTS5lnK64',
    appId: '1:884151832412:android:77a3baad09a8b008fabb99',
    messagingSenderId: '884151832412',
    projectId: 'promisee-30dd7',
    storageBucket: 'promisee-30dd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNhtUvsHpDhoL-gesTZ_KH0O64KXy5GY0',
    appId: '1:884151832412:ios:d23a638f5168c87dfabb99',
    messagingSenderId: '884151832412',
    projectId: 'promisee-30dd7',
    storageBucket: 'promisee-30dd7.appspot.com',
    iosBundleId: 'com.example.promisee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNhtUvsHpDhoL-gesTZ_KH0O64KXy5GY0',
    appId: '1:884151832412:ios:4a28658f7e2d1599fabb99',
    messagingSenderId: '884151832412',
    projectId: 'promisee-30dd7',
    storageBucket: 'promisee-30dd7.appspot.com',
    iosBundleId: 'com.example.promisee.RunnerTests',
  );
}
